trigger: none
pr: none

variables:
  - name: stage_set
    value: '[{"duration":"10m","target":5000},{"duration":"20m","target":5000},{"duration":"20m","target":20000},{"duration":"10m","target":0}]'

stages:
  - stage: LoadTest
    displayName: "Load Test with Tag"
    jobs:
      - job: LoadTestJob
        displayName: "Run Load Test"
        pool:
          name: 'QualityAssurance'
        steps:
          - checkout: self

          - script: |
              gpg -k
              curl -fsSL https://dl.k6.io/key.gpg | gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
              echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | tee /etc/apt/sources.list.d/k6.list
              apt-get update
              apt-get install k6
            displayName: "Install k6"

          - script: |
              k6 run src/index.js --out influxdb=http://prometheus:9090 --env STAGES_SET='$(stage_set)' --env HAS_LOG=true --env ENV=dev
            displayName: "exec k6"
            continueOnError: true

          - task: PublishBuildArtifacts@1
            displayName: 'Azure - Publish Build Artifacts'
            inputs:
              PathtoPublish: summary.html
              ArtifactName: drop