global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "k6"
    static_configs:
      - targets: ["host.docker.internal:6565"]

remote_write:
  - url: "http://prometheus:9090/api/v1/write"